export const INIT_AUCTION = "INIT_AUCTION";
export const ADD_FOR_AUCTION = "ADD_FOR_AUCTION";
export const REMOVE_FOR_AUCTION = "REMOVE_FOR_AUCTION";
export const CLEAR_AUCTION = "CLEAR_AUCTION";
export const ADD_BID_COIN_AUCTION = "ADD_BID_COIN_AUCTION";
export const END_COIN_AUCTION = "END_COIN_AUCTION";
export const END_AUCTION_REQUEST = "END_AUCTION_REQUEST";
export const END_AUCTION_RESPONSE = "END_AUCTION_RESPONSE";
